name-template: 'v$NEXT_PATCH_VERSION' # defaults to patch version
tag-template: 'v$NEXT_PATCH_VERSION'

branches:
  - master

categories:
  - title: ðŸ’¥ Breaking Changes
    label: 'BREAKING CHANGE'

  - title: âœ¨ Features
    label: 'feat'

  - title: ðŸ› Bug Fixes
    label: 'fix'

  - title: ðŸš€ Improvements
    label: 'perf'

  - title: ðŸ”§ Code Improvements
    label: 'refactor'

  - title: ðŸš§ Maintenance
    label: 'chore'

  - title: ðŸ‘· CI/CD
    label: 'ci'

  - title: ðŸ”© Build
    label: 'build'

  - title: ðŸ’¯ Tests
    label: 'test'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Changes
  $CHANGES

replacers:
  # e.g. chore: change xxx -> change xxx
  - search: '/(?:feat:|fix:|perf:|refactor:|chore:|ci:|build:|test:)\s*/g'
    replace: ''
  # e.g. feat(web): add xxx -> web: add xxx
  - search: '/(?:feat|fix|perf|refactor|chore|ci|build|test)\((\w+)\):\s*/g'
    replace: '$1: '

  # For capitalizing the first letter in every bullet point
  - search: '/^\s*\W+\s*a/g'
    replace: 'A'

  - search: '/^\s*\W+\s*b/g'
    replace: 'B'

  - search: '/^\s*\W+\s*c/g'
    replace: 'C'

  - search: '/^\s*\W+\s*d/g'
    replace: 'D'

  - search: '/^\s*\W+\s*e/g'
    replace: 'E'

  - search: '/^\s*\W+\s*f/g'
    replace: 'F'

  - search: '/^\s*\W+\s*g/g'
    replace: 'G'

  - search: '/^\s*\W+\s*h/g'
    replace: 'H'

  - search: '/^\s*\W+\s*i/g'
    replace: 'I'

  - search: '/^\s*\W+\s*j/g'
    replace: 'J'

  - search: '/^\s*\W+\s*k/g'
    replace: 'K'

  - search: '/^\s*\W+\s*l/g'
    replace: 'L'

  - search: '/^\s*\W+\s*m/g'
    replace: 'M'

  - search: '/^\s*\W+\s*n/g'
    replace: 'N'

  - search: '/^\s*\W+\s*o/g'
    replace: 'O'

  - search: '/^\s*\W+\s*p/g'
    replace: 'P'

  - search: '/^\s*\W+\s*q/g'
    replace: 'Q'

  - search: '/^\s*\W+\s*r/g'
    replace: 'R'

  - search: '/^\s*\W+\s*s/g'
    replace: 'S'

  - search: '/^\s*\W+\s*t/g'
    replace: 'T'

  - search: '/^\s*\W+\s*u/g'
    replace: 'U'

  - search: '/^\s*\W+\s*v/g'
    replace: 'V'

  - search: '/^\s*\W+\s*w/g'
    replace: 'W'

  - search: '/^\s*\W+\s*x/g'
    replace: 'X'

  - search: '/^\s*\W+\s*y/g'
    replace: 'Y'

  - search: '/^\s*\W+\s*z/g'
    replace: 'Z'
