name-template: 'v$NEXT_PATCH_VERSION' # defaults to patch version
tag-template: 'v$NEXT_PATCH_VERSION'

branches:
  - master

categories:
  - title: 💥 Breaking Changes
    label: 'BREAKING CHANGE'

  - title: ✨ Features
    label: 'feat'

  - title: 🐛 Bug Fixes
    label: 'fix'

  - title: 🚀 Improvements
    label: 'perf'

  - title: 🔧 Code Improvements
    label: 'refactor'

  - title: 🚧 Maintenance
    label: 'chore'

  - title: 👷 CI/CD
    label: 'ci'

  - title: 🔩 Build
    label: 'build'

  - title: 💯 Tests
    label: 'test'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Changes
  $CHANGES

replacers:
  # e.g. feat(web): add xxx -> web: add xxx
  - search: '/(?:feat|fix|perf|refactor|chore|ci|build|test)\((\w+)\):\s*/g'
    replace: '$1: '
  # e.g. chore: change xxx -> change xxx
  - search: '/(?:feat:|fix:|perf:|refactor:|chore:|ci:|build:|test:)\s*/g'
    replace: ''

  # For capitalizing the first letter in every sentence
  - search: '/^a/g'
    replace: 'A'

  - search: '/^b/g'
    replace: 'B'

  - search: '/^c/g'
    replace: 'C'

  - search: '/^d/g'
    replace: 'D'

  - search: '/^e/g'
    replace: 'E'

  - search: '/^f/g'
    replace: 'F'

  - search: '/^g/g'
    replace: 'G'

  - search: '/^h/g'
    replace: 'H'

  - search: '/^i/g'
    replace: 'I'

  - search: '/^j/g'
    replace: 'J'

  - search: '/^k/g'
    replace: 'K'

  - search: '/^l/g'
    replace: 'L'

  - search: '/^m/g'
    replace: 'M'

  - search: '/^n/g'
    replace: 'N'

  - search: '/^o/g'
    replace: 'O'

  - search: '/^p/g'
    replace: 'P'

  - search: '/^q/g'
    replace: 'Q'

  - search: '/^r/g'
    replace: 'R'

  - search: '/^s/g'
    replace: 'S'

  - search: '/^t/g'
    replace: 'T'

  - search: '/^u/g'
    replace: 'U'

  - search: '/^v/g'
    replace: 'V'

  - search: '/^w/g'
    replace: 'W'

  - search: '/^x/g'
    replace: 'X'

  - search: '/^y/g'
    replace: 'Y'

  - search: '/^z/g'
    replace: 'Z'
