name-template: 'v$NEXT_PATCH_VERSION' # defaults to patch version
tag-template: 'v$NEXT_PATCH_VERSION'

branches:
  - master

categories:
  - title: ðŸ’¥ Breaking Changes
    label: 'BREAKING CHANGE'

  - title: âœ¨ Features
    label: 'feat'

  - title: ðŸ› Bug Fixes
    label: 'fix'

  - title: ðŸš€ Improvements
    label: 'perf'

  - title: ðŸ”§ Code Improvements
    label: 'refactor'

  - title: ðŸš§ Maintenance
    label: 'chore'

  - title: ðŸ‘· CI/CD
    label: 'ci'

  - title: ðŸ”© Build
    label: 'build'

  - title: ðŸ’¯ Tests
    label: 'test'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Changes
  $CHANGES

replacers:
  # e.g. feat(web): add xxx -> Web: Add xxx
  - search: '(?:feat|fix|perf|refactor|chore|ci|build|test)\((\w)(\w*)\)\s*(\w)'
    replace: '\L$1$2: $3'
  # e.g. chore: change xxx -> Change xxx
  - search: '(?:feat:|fix:|perf:|refactor:|chore:|ci:|build:|test:)\s*(\w)'
    replace: '\L$1'
